<script lang="ts" context="module">
	export const langNames: Record<string, string> = {
		akk: 'Akkadian',
		amh: 'Amharic',
		ara: 'Arabic',
		arc: 'Official Aramaic (700-300 BCE)',
		atz: 'Arta',
		ave: 'Avestan',
		bam: 'Bambara',
		bod: 'Tibetan',
		bqi: 'Bakhtiari',
		cop: 'Coptic',
		dar: 'Dargwa',
		deu: 'German',
		efi: 'Efik',
		elx: 'Elamite',
		eng: 'English',
		erk: 'South Efate',
		fas: 'Persian',
		fra: 'French',
		ful: 'Fulah',
		gez: 'Geez',
		grc: 'Ancient Greek (to 1453)',
		hac: 'Gurani',
		heb: 'Hebrew',
		hit: 'Hittite',
		hye: 'Armenian',
		ind: 'Indonesian',
		jpn: 'Japanese',
		kac: 'Kachin',
		kan: 'Kannada',
		kbl: 'Kanembu',
		kgv: 'Karas',
		khm: 'Khmer',
		kur: 'Kurdish',
		lat: 'Latin',
		mal: 'Malayalam',
		mku: 'Konyanka Maninka',
		mlt: 'Maltese',
		mzn: 'Mazanderani',
		nep: 'Nepali (macrolanguage)',
		nld: 'Flemish',
		por: 'Portuguese',
		que: 'Quechua',
		rus: 'Russian',
		san: 'Sanskrit',
		snk: 'Soninke',
		spa: 'Spanish',
		sux: 'Sumerian',
		swe: 'Swedish',
		syr: 'Syriac',
		tab: 'Tabassaran',
		tam: 'Tamil',
		tdn: 'Tondano',
		tio: 'Teop',
		tir: 'Tigrinya',
		tks: 'Takestani',
		tru: 'Turoyo',
		tuh: 'Taulil',
		tur: 'Turkish',
		uga: 'Ugaritic',
		urd: 'Urdu',
		vra: "Vera'a",
		xeb: 'Eblan',
		xsa: 'Sabaean',
		xur: 'Urartian',
		yid: 'Yiddish',
		yor: 'Yoruba',
		zho: 'Chinese',
		zum: 'Kumzari'
	};
</script>
