name: Archive GitHub Pages

on:
  schedule:
    - cron: "20 4 1 * *"
  workflow_dispatch:

jobs:
  archive:
    name: Submit URL to Internet Archive

    runs-on: ubuntu-latest

    steps:
      - uses: caltechlibrary/waystation@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          debug: true
          dry_run: false
