on:
  workflow_dispatch:

jobs:
  archive:
    name: Submit website URL to the Internet Archive

    runs-on: ubuntu-latest

    steps:
      - uses: caltechlibrary/waystation@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          debug: true
