name: Archive GitHub Pages

on:
  schedule:
    - cron: "20 4 1 * *"
  workflow_dispatch:
    inputs:
      dry_run:
        description: Run without actually submitting URL
        type: boolean

jobs:
  archive:
    name: Submit URL to Internet Archive

    runs-on: ubuntu-latest

    steps:
      - uses: caltechlibrary/waystation@v1.8
        with:
          debug: true
          dry_run: ${{github.event.inputs.dry_run || false}}
