name: CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON
        uses: Closing-the-Gap-in-NLS-DH/project-validator
        with:
          input_folder: '/PROJECTS/**'  