name: CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON
        uses: nhalstead/validate-json-action@0.1.3
        env:
          INPUT_SCHEMA: /SCHEMATA/project.schema.json
          INPUT_JSONS: /PROJECTS/**